const CATS = {
    wildCat: {
        id: "wildCat",
        name: "길 고양이",
        cost: 1,
        ad: 10,
        speed: 10,
        hp: 120,
        armor: 2,
        range: 1,
    },
    thiefCat: {
        id: "thiefCat",
        name: "도둑 고양이",
        cost: 1,
        ad: 10,
        speed: 20,
        hp: 80,
        armor: 1,
        range: 1,
    },
    strongCat: {
        id: "strongCat",
        name: "강한 고양이",
        cost: 2,
        ad: 25,
        speed: 8,
        hp: 130,
        armor: 4,
        range: 1,
    },
    ssepCat: {
        id: "ssepCat",
        name: "쌥쌥 고양이",
        cost: 2,
        ad: 10,
        speed: 35,
        hp: 100,
        armor: 1,
        range: 3,
    },
    tankCat: {
        id: "tankCat",
        name: "탱크 고양이",
        cost: 3,
        ad: 15,
        speed: 8,
        hp: 150,
        armor: 8,
        range: 2,
    },
    adCat: {
        id: "adCat",
        name: "원딜 고양이",
        cost: 3,
        ad: 17,
        speed: 20,
        hp: 100,
        armor: 1,
        range: 4,
    },
    assasinCat: {
        id: "assasinCat",
        name: "암살자 고양이",
        cost: 4,
        ad: 100,
        speed: 20,
        hp: 30,
        armor: 0,
        range: 1,
    },
    armorCat: {
        id: "armorCat",
        name: "철갑 고양이",
        cost: 4,
        ad: 15,
        speed: 5,
        hp: 200,
        armor: 18,
        range: 1,
    },

    // creep
    // eel: {
    //     id: "eel",
    //     name: "뱀장어",
    //     cost: 1,
    //     ad: 10,
    //     speed: 10,
    //     hp: 50,
    //     armor: 3,
    //     range: 2,
    // },
    // crab: {
    //     id: "crab",
    //     name: "게",
    //     cost: 2,
    //     ad: 20,
    //     speed: 20,
    //     hp: 90,
    //     armor: 5,
    //     range: 1,
    // },
};
Object.freeze(CATS);
module.exports = CATS;
